# See: https://dart.dev/tools/pub/pubspec
name: foobar
version: 0.0.0
description: >-
  TODO for Dart (60-180 characters)
homepage: https://github.com/drydart/foobar
repository: https://github.com/drydart/foobar
issue_tracker: https://github.com/drydart/foobar/issues
documentation:
dependencies:
  meta: ^1.1.8
dev_dependencies:
  test: any
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
executables:
publish_to: none
